[project]
name = "gdpr-obfuscator-infrastructure"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.7"
dependencies = []

[dependency-groups]
dev = [
    "pulumi>=3.197.0",
    "pulumi-aws>=7.7.0",
]
