name: gdpr-obfuscator-infrastructure
description: Infrastructure deployment for a Python library for obfuscating personally identifiable information (PII) in CSV files for GDPR compliance
runtime:
  name: python
  options:
    toolchain: uv
config:
  pulumi:tags:
    value:
      pulumi:template: aws-python
